name: Lit Protocol Network Connectivity Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   - cron: '0 */6 * * *'  # Run every 6 hours to monitor network stability

jobs:
  test-network-connectivity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        # Disable caching completely if still having issues
        # cache: 'npm'
        
    - name: Install and Test
      run: |
        npm ci
        npx ts-node test/network-connectivity.test.ts
      timeout-minutes: 4
      
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Network Connectivity Test Failed',
            body: 'The network connectivity test failed in the latest run. Please check the [workflow run](' + 
                  `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}` + 
                  ') for details.'
          }) 